Делает авторизацию
htmlacademy-php/103121-yeticave-12 pull request #13
Opened 2020-07-27 16:04 UTC by artytrik

2020-07-28 10:54 UTC, shershnevsergey requested changes

2020-07-28 10:54 UTC, Shv-sergey70 commented on login.php
> +$title = 'Авторизация';
Переменная используется только в одном месте, так что можно без нее. Можно сразу писать значение в массиве в `include_template `

2020-07-28 10:54 UTC, Shv-sergey70 commented on login.php
> +        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
Эту проверку можно сделать еще до запроса к БД, потому что если она не пройдет - то будет лишний запрос к БД

2020-07-28 10:54 UTC, Shv-sergey70 commented on login.php
> +                $errors['password'] = 'Неверный пароль';
Сложная конструкция с присваиванием в тернарном операторе - лучше это упростить

2020-07-28 10:54 UTC, Shv-sergey70 commented on login.php
> +} else if (isset($_SESSION['user'])) {
Это условие лучше перенести в самое начало, до всевозможных действий, потому что если юзер залогинен - надо сразу делать редирект

2020-07-28 10:54 UTC, Shv-sergey70 commented on sign-up.php
> +    http_response_code(403);
Для 403 стоит завести константу

2020-07-28 10:54 UTC, Shv-sergey70 commented on templates/layout.php
> +                <?php if (isset($_SESSION['user'])): ?>
Лучше не использовать напрямую суперглобальный массив `$_SESSION` в шаблонах. Все что мы используем в шаблонах стоит передавать ТОЛЬКО через `include_template` - это дает гарантию единого места, откуда мы имеет переменные и не зависим от сессии

2020-07-28 10:54 UTC, Shv-sergey70 commented on templates/lot.php
> +                        <?= get_time_range(htmlspecialchars($lot['finish_date'], ENT_QUOTES))[0] >= 1
`finish_date` - это то, что мы записываем в БД с типом `Date`, так что `htmlspecialchars` не обязателен

2020-07-28 10:54 UTC, Shv-sergey70 commented on templates/lot.php
> +                            <span class="lot-item__cost"><?= format_price(htmlspecialchars($lot['price'], ENT_QUOTES)); ?></span>
Цена также хранится числом, так что экранирование не обязательно. Вообще экранировать имеет смысл строковые данные

2020-07-28 10:54 UTC, Shv-sergey70 commented on sign-up.php
> +if (!isset($_SESSION['user'])) {
А как новым пользователям регистрироваться при этом условии?

2020-07-28 10:54 UTC, Shv-sergey70 commented on sign-up.php
> +if (!isset($_SESSION['user'])) {
> По такому же принципу для залогиненных пользователей надо закрыть страницу регистрации.

2020-07-28 10:56 UTC, artytrik commented on login.php
> +                $errors['password'] = 'Неверный пароль';
Упрощение - это использование if/else?

2020-07-28 10:57 UTC, artytrik commented on sign-up.php
> +    http_response_code(403);
А нужен отдельный файл для констант?

2020-07-28 20:10 UTC, artytrik commented on templates/layout.php
> +                <?php if (isset($_SESSION['user'])): ?>
А как правильно передавать значение массива через include_template?

2020-07-29 05:44 UTC, Shv-sergey70 commented on login.php
> +                $errors['password'] = 'Неверный пароль';
Как вариант - да.
Просто не стоит присваивать переменным значения в операндах тернарного оператора

2020-07-29 05:45 UTC, Shv-sergey70 commented on sign-up.php
> +    http_response_code(403);
Да, либо в `init`. Но лучше отдельный файл

2020-07-29 05:47 UTC, Shv-sergey70 commented on templates/layout.php
> +                <?php if (isset($_SESSION['user'])): ?>
```
$layout_content = include_template('layout.php',
    [
        'content' => $page_content,
        'title' => $title,
        'categories' => $categories,
        'user' => $_SESSION['user'] ?? null
    ]
);
```

```
<nav class="user-menu">
                <?php if (isset($user)): ?>
                    <div class="user-menu__logged">
                        <p><?= $_SESSION['user']['name']; ?></p>
                        <a class="user-menu__bets" href="pages/my-bets.html">Мои ставки</a>
                        <a class="user-menu__logout" href="logout.php">Выход</a>
                    </div>
                <?php else: ?>
                    <ul class="user-menu__list">
                        <li class="user-menu__item">
                        <a href="sign-up.php">Регистрация</a>
                        </li>
                        <li class="user-menu__item">
                        <a href="login.php">Вход</a>
                        </li>
                    </ul>
                <?php endif ?>
            </nav>
```

2020-07-29 07:09 UTC, artytrik commented on login.php
> +                $errors['password'] = 'Неверный пароль';
Пока оставляю так как есть, может быть придумаем какое-то другое решение.

2020-07-29 08:35 UTC, Shv-sergey70 commented on const.php
> +$forbidden_error = 403;
Речь о таких константах 
https://www.php.net/manual/ru/language.constants.php

```
<?php

const FORBIDDEN_ERROR = 403;
```

Либо через define

2020-07-29 09:12 UTC, merged